services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverseproxy
    ports:
      - 80:80
    networks:
      - pacman-network

  pacman-hiscores-webapp:
    image: dockerimage:latest
    ports:
      - 5000:5000
    networks:
      - pacman-network

  db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    volumes:
      - db-data:/data
    networks:
      - pacman-network
    ports:
      - 27017:27017

volumes:
  db-data:

networks:
  pacman-network: